#!/usr/bin/env python3
"""Generate an HTML comparison report: user ('mine') regex vs new researcher regex.

Reads regex_comparison.json for user patterns and *_regex_patterns.json for
researcher patterns, then produces comparison_report_new.html with per-condition
analysis generated by Bedrock Claude.
"""

import html
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from utils.bedrock_client import invoke_claude, load_config
from utils.paths import slugify

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
COMPARISON_FILE = os.path.join(SCRIPT_DIR, "regex_comparison.json")
RESEARCHER_FILE = os.path.join(os.path.dirname(SCRIPT_DIR), "researcher_regex_export.json")
RESULTS_DIR = os.path.join(SCRIPT_DIR, "results")
OUTPUT_HTML = os.path.join(RESULTS_DIR, "coverage_report.html")

ANALYSIS_PROMPT = """You are a regex comparison analyst.  Given:
- CONDITION: {condition}
- USER REGEX ("mine"):  {mine_regex}
- RESEARCHER REGEX:     {researcher_regex}

Produce a JSON object (no markdown fences) with these fields:
{{
  "coverage_pct": <integer 0-100>,
  "badges": ["<badge text>", ...],
  "conditions": [
    {{"name": "<condition name>", "status": "tick|cross|warn|plus", "notes": "<one-line note>"}},
    ...
  ],
  "note": "<one-line summary note>"
}}

Rules for analysis:
- coverage_pct = what % of the researcher's structural conditions does "mine" satisfy.
- "tick" = condition fully met, "cross" = missing, "warn" = partially met, "plus" = mine is stricter (bonus).
- Be specific about structural differences: separators, character classes, alternation branches, length.
- If mine is stricter on a dimension (e.g. restricts to valid ranges), that's a "plus" bonus.
- If researcher handles optional separators (space/hyphen) that mine doesn't, mark as "cross" or "warn".
- Return ONLY valid JSON."""


def load_entries() -> list[dict]:
    with open(COMPARISON_FILE) as f:
        mine_entries = json.load(f)

    # Build slug → researcher_regex from researcher_regex_export.json
    researcher_map = {}
    if os.path.exists(RESEARCHER_FILE):
        with open(RESEARCHER_FILE) as f:
            researcher_entries = json.load(f)
        for e in researcher_entries:
            slug = e.get("slug", "")
            rx = e.get("researcher_regex")
            if slug and rx:
                researcher_map[slug] = rx

    # Merge researcher regex into each mine entry
    for e in mine_entries:
        slug = e.get("slug", "")
        e["_researcher"] = researcher_map.get(slug)

    return mine_entries


def get_researcher_regex(entry: dict) -> "str | None":
    """Get researcher regex from the merged entry."""
    return entry.get("_researcher")


def strip_wb(regex_str: str) -> str:
    """Strip \\b word boundaries for display comparison."""
    r = regex_str
    if r.startswith("\\b"):
        r = r[2:]
    if r.endswith("\\b"):
        r = r[:-2]
    return r


def analyze_pair(condition: str, mine: str, researcher: str, config: dict) -> dict:
    """Use LLM to produce structured comparison."""
    prompt = ANALYSIS_PROMPT.format(
        condition=condition,
        mine_regex=mine,
        researcher_regex=researcher,
    )
    raw = invoke_claude(prompt, config)
    raw = raw.strip()
    if raw.startswith("```"):
        lines = raw.splitlines()
        lines = [l for l in lines if not l.strip().startswith("```")]
        raw = "\n".join(lines).strip()
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        return {
            "coverage_pct": 50,
            "badges": [],
            "conditions": [{"name": "Parse error", "status": "warn", "notes": "LLM response was not valid JSON"}],
            "note": f"Raw: {raw[:200]}",
        }


def _esc(text: str) -> str:
    return html.escape(text, quote=True)


def _badge_class(pct: int) -> str:
    if pct >= 75:
        return "badge-high"
    if pct >= 40:
        return "badge-mid"
    return "badge-low"


def _status_span(status: str) -> str:
    mapping = {
        "tick": '<span class="tick">✓</span>',
        "cross": '<span class="cross">✗</span>',
        "warn": '<span class="warn">~</span>',
        "plus": '<span class="plus">+1</span>',
    }
    return mapping.get(status, status)


def build_html(entries: list[dict], analyses: dict[str, dict]) -> str:
    """Build the full HTML report."""

    high = sum(1 for a in analyses.values() if a.get("coverage_pct", 0) >= 75)
    mid = sum(1 for a in analyses.values() if 40 <= a.get("coverage_pct", 0) < 75)
    low = sum(1 for a in analyses.values() if a.get("coverage_pct", 0) < 40)
    total = len(analyses)
    avg_cov = round(sum(a.get("coverage_pct", 0) for a in analyses.values()) / max(total, 1))

    entry_blocks: list[str] = []
    for i, entry in enumerate(entries, 1):
        slug = entry["slug"]
        mine_display = strip_wb(entry["mine"])
        analysis = analyses.get(slug)
        if analysis is None:
            continue
        researcher_display = strip_wb(analysis.get("_researcher_regex", "N/A"))
        pct = analysis.get("coverage_pct", 0)
        badges_html = f'<span class="badge {_badge_class(pct)}">{pct}% coverage</span>'
        for b in analysis.get("badges", []):
            badges_html += f' <span class="badge badge-better">{_esc(b)}</span>'

        rows = ""
        for c in analysis.get("conditions", []):
            rows += (
                f'<tr><td>{_esc(c["name"])}</td>'
                f'<td>{_status_span(c["status"])}</td>'
                f'<td>{c["notes"]}</td></tr>\n'
            )

        note = _esc(analysis.get("note", ""))

        block = f"""
  <div class="entry">
    <div class="entry-header">
      <div class="entry-title">{i}. {_esc(entry["condition"].title())}</div>
      {badges_html}
    </div>
    <div class="regexes">
      <div class="regex-col"><div class="regex-label">Mine</div><div class="regex-val">{_esc(mine_display)}</div></div>
      <div class="regex-col"><div class="regex-label">Researcher (new)</div><div class="regex-val">{_esc(researcher_display)}</div></div>
    </div>
    <table class="cond-table">
      <tr><th>Condition</th><th>Status</th><th>Notes</th></tr>
      {rows}
    </table>
    <div class="note"><span>Summary:</span> {note}</div>
  </div>
"""
        entry_blocks.append(block)

    entries_html = "\n".join(entry_blocks)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Regex Comparison Report (New Pipeline)</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; background: #0f1117; color: #e2e8f0; font-size: 14px; line-height: 1.6; }}
  .page {{ max-width: 1300px; margin: 0 auto; padding: 32px 24px; }}

  h1 {{ font-size: 22px; font-weight: 700; color: #f8fafc; margin-bottom: 4px; }}
  .subtitle {{ color: #64748b; font-size: 13px; margin-bottom: 32px; }}

  .summary-grid {{ display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin-bottom: 36px; }}
  .stat {{ background: #1e2330; border: 1px solid #2d3748; border-radius: 10px; padding: 16px 20px; }}
  .stat-val {{ font-size: 28px; font-weight: 700; }}
  .stat-lbl {{ color: #64748b; font-size: 12px; margin-top: 2px; }}
  .green  {{ color: #34d399; }} .yellow {{ color: #fbbf24; }} .red {{ color: #f87171; }} .blue {{ color: #60a5fa; }}

  .bar-wrap {{ background: #1e2330; border: 1px solid #2d3748; border-radius: 10px; padding: 20px 24px; margin-bottom: 36px; }}
  .bar-wrap h2 {{ font-size: 13px; color: #94a3b8; font-weight: 600; margin-bottom: 12px; letter-spacing: .05em; text-transform: uppercase; }}
  .bar-outer {{ background: #2d3748; border-radius: 99px; height: 10px; overflow: hidden; }}
  .bar-inner {{ height: 100%; border-radius: 99px; background: linear-gradient(90deg,#34d399,#60a5fa); }}
  .bar-label {{ font-size: 12px; color: #94a3b8; margin-top: 6px; }}

  .entry {{ background: #1e2330; border: 1px solid #2d3748; border-radius: 12px; margin-bottom: 28px; overflow: hidden; }}
  .entry-header {{ display: flex; align-items: center; gap: 12px; padding: 14px 20px; border-bottom: 1px solid #2d3748; background: #161b27; }}
  .entry-title {{ font-weight: 700; font-size: 15px; flex: 1; }}
  .badge {{ font-size: 11px; font-weight: 700; padding: 3px 10px; border-radius: 99px; white-space: nowrap; }}
  .badge-high   {{ background: #064e3b; color: #34d399; }}
  .badge-mid    {{ background: #451a03; color: #fbbf24; }}
  .badge-low    {{ background: #450a0a; color: #f87171; }}
  .badge-better {{ background: #1e3a5f; color: #60a5fa; }}

  .regexes {{ display: grid; grid-template-columns: 1fr 1fr; gap: 0; border-bottom: 1px solid #2d3748; }}
  .regex-col {{ padding: 12px 20px; }}
  .regex-col:first-child {{ border-right: 1px solid #2d3748; }}
  .regex-label {{ font-size: 11px; color: #64748b; font-weight: 600; text-transform: uppercase; letter-spacing: .06em; margin-bottom: 6px; }}
  .regex-val {{ font-family: "SF Mono", "Fira Code", monospace; font-size: 11.5px; color: #a78bfa; word-break: break-all; background: #0f1117; padding: 8px 10px; border-radius: 6px; border: 1px solid #2d3748; }}

  .cond-table {{ width: 100%; border-collapse: collapse; }}
  .cond-table th {{ font-size: 11px; color: #64748b; text-transform: uppercase; letter-spacing: .06em; padding: 8px 16px; text-align: left; border-bottom: 1px solid #2d3748; }}
  .cond-table td {{ padding: 9px 16px; font-size: 13px; border-bottom: 1px solid #1a2035; vertical-align: top; }}
  .cond-table tr:last-child td {{ border-bottom: none; }}
  .cond-table td:nth-child(1) {{ color: #cbd5e1; width: 32%; }}
  .cond-table td:nth-child(2) {{ width: 11%; text-align: center; font-size: 13px; }}
  .cond-table td:nth-child(3) {{ color: #94a3b8; font-size: 12px; }}

  .tick   {{ color: #34d399; }}
  .cross  {{ color: #f87171; }}
  .plus   {{ color: #60a5fa; }}
  .warn   {{ color: #fbbf24; }}

  .note {{ padding: 10px 20px 14px; font-size: 12px; color: #64748b; border-top: 1px solid #1a2035; }}
  .note span {{ color: #94a3b8; }}
</style>
</head>
<body>
<div class="page">

  <h1>Regex Coverage Report — Mine vs Researcher (New Pipeline)</h1>
  <div class="subtitle">Per-condition analysis after pipeline improvements (policy-backed restrictions, statistical observations, deterministic separators)</div>

  <div class="summary-grid">
    <div class="stat"><div class="stat-val green">{high}</div><div class="stat-lbl">High coverage >= 75%</div></div>
    <div class="stat"><div class="stat-val yellow">{mid}</div><div class="stat-lbl">Mid coverage 40-74%</div></div>
    <div class="stat"><div class="stat-val red">{low}</div><div class="stat-lbl">Low coverage &lt; 40%</div></div>
    <div class="stat"><div class="stat-val blue">{total}</div><div class="stat-lbl">Total entries compared</div></div>
  </div>

  <div class="bar-wrap">
    <h2>Overall weighted coverage</h2>
    <div class="bar-outer"><div class="bar-inner" style="width:{avg_cov}%"></div></div>
    <div class="bar-label">{avg_cov}% average condition coverage across all {total} entries</div>
  </div>

  {entries_html}

  <div style="background:#1e2330;border:1px solid #2d3748;border-radius:10px;padding:16px 24px;margin-top:8px;font-size:12px;color:#64748b;">
    <b style="color:#94a3b8;">Legend:</b>&nbsp;
    <span class="tick">✓</span> Condition met &nbsp;
    <span class="cross">✗</span> Condition missing &nbsp;
    <span class="warn">~</span> Partially met / minor diff &nbsp;
    <span class="plus">+1</span> Stricter than researcher (bonus) &nbsp;&nbsp;
    <b style="color:#94a3b8;">Coverage score</b> = (met + 0.5 x partial + bonus) / total researcher conditions x 100
  </div>

</div>
</body>
</html>"""


def main() -> None:
    config = load_config(os.path.join(SCRIPT_DIR, "config.yaml"))
    entries = load_entries()
    print(f"Loaded {len(entries)} conditions")

    analyses: dict[str, dict] = {}

    for i, entry in enumerate(entries, 1):
        slug = entry["slug"]
        condition = entry["condition"]
        mine = entry["mine"]
        researcher = get_researcher_regex(entry)

        if not researcher:
            print(f"  [{i}] {condition}: NO RESEARCHER REGEX — skipping")
            continue

        if "java" in slug:
            print(f"  [{i}] {condition}: skipping java")
            continue

        print(f"  [{i}] Analyzing: {condition}")
        analysis = analyze_pair(condition, mine, researcher, config)
        analysis["_researcher_regex"] = researcher
        analyses[slug] = analysis

    report_html = build_html(entries, analyses)
    with open(OUTPUT_HTML, "w", encoding="utf-8") as f:
        f.write(report_html)
    print(f"\nReport written to {OUTPUT_HTML}")


if __name__ == "__main__":
    main()
